services:
  github-sponsor-discord-notifier:
    image: ghcr.io/thelovinator1/github-sponsor-discord-notifier:latest
    env_file:
      - .env
    container_name: github-sponsor-discord-notifier
    environment:
      - WEBHOOK_URL=${WEBHOOK_URL}
    expose:
      - 5000
    restart: unless-stopped
