name: Test and build Docker image

on:
  schedule:
    - cron: "20 6 * * *"
  push:
  pull_request:
  workflow_dispatch:
env:
  WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - run: pipx install poetry
      - run: poetry install
      - run: poetry run pytest
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    if: github.event_name != 'pull_request'
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: .
          tags: ghcr.io/thelovinator1/github-sponsor-discord-notifier:latest
